### PR TITLE
Fix modals, broken images, overly large images.

### PR DESCRIPTION
**Pull request by rockon999**
- Ensure content images aren't massive.
- Update missing "image" to be less obtrusive.
- Fix some preview bugs.

### CODE REVIEW

**Comment by SamChou19815** [comment]
Not sure why the netlify jobs are broken and sometimes inconsistent with CI results.

**Comment by rockon999** [comment]
@SamChou19815 I'm trying to figure that out myself.

**Comment by rockon999** [comment]
@SamChou19815 So I had to make some custom packages because of the way gridsome detects plugins. The way I currently "install" them is admittedly somewhat hacky. Netlify caches dependencies, so when one of the custom packages is updated it can cause the first CI run to fail.

Looking into better ways to handle custom packages.

**Comment by SamChou19815** [comment]
Maybe Yarn workspace can help
- https://classic.yarnpkg.com/en/docs/workspaces
- https://www.netlify.com/blog/2019/10/09/launching-monorepo-support-for-netlify-sites/

**Pull request merged**
